approvedGitRepositories:
  - "https://npm-registry.sipwise.com/*"

enableScripts: true

npmMinimalAgeGate: 0

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.1.cjs

npmRegistryServer: "https://npm-registry.sipwise.com/"


