approvedGitRepositories:
  - "https://npm-registry.sipwise.com/*"

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmAuditExcludePackages:
  - vue-template-compiler

npmMinimalAgeGate: 0

npmRegistryServer: "https://npm-registry.sipwise.com/"

yarnPath: .yarn/releases/yarn-4.18.1.cjs
