export const APP_NAME = 'CSC'

export const INTERNAL_DATE_FORMAT_SLASH = 'YYYY/MM/DD'

export const INTERNAL_DATE_FORMAT_DASH = 'YYYY-MM-DD'

export const INTERNAL_DATE_FORMAT_DASH_HOUR = 'YYYY-MM-DD HH:mm'
